
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;
	private global::Gtk.ToggleButton togglebutton1;
	private global::Gtk.SpinButton spinbutton1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.togglebutton1 = new global::Gtk.ToggleButton ();
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
		this.fixed2.Add (this.togglebutton1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.togglebutton1]));
		w1.X = 103;
		w1.Y = 250;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.spinbutton1 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10D;
		this.spinbutton1.ClimbRate = 1D;
		this.spinbutton1.Numeric = true;
		this.fixed2.Add (this.spinbutton1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.spinbutton1]));
		w2.X = 101;
		w2.Y = 181;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 525;
		this.DefaultHeight = 360;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
